backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:

  # Edit your profile (bio, role, email)
  - name: "author"
    label: "Author Profile"
    files:
      - label: "Admin"
        name: "admin"
        file: "content/authors/admin/_index.md"
        fields:
          - { label: "Name", name: "title", widget: "string" }
          - { label: "Role", name: "role", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Organization", name: "organization", widget: "string", required: false }
          - { label: "Biography", name: "bio", widget: "text" }
          - { label: "Avatar", name: "avatar", widget: "image", required: false }

  # Teaching section
  - name: "teaching"
    label: "Teaching Section"
    files:
      - label: "Teaching Content"
        name: "teaching"
        file: "content/home/teaching.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

  # CV link section
  - name: "cv"
    label: "CV Section"
    files:
      - label: "CV Block"
        name: "cv"
        file: "content/home/cv.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Button Text", name: "cta", widget: "string" }
          - { label: "PDF File Path", name: "file", widget: "string", hint: "Example: files/sianlee_cv.pdf" }

  # Homepage About section
  - name: "about"
    label: "About Section"
    files:
      - label: "About Block"
        name: "about"
        file: "content/home/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  # Publications
  - name: "publications"
    label: "Publications"
    folder: "content/publication"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Publish", name: "publishDate", widget: "datetime" }
      - { label: "Authors", name: "authors", widget: "list", default: ["Sian Lee"] }
      - { label: "Publication", name: "publication", widget: "string" }
      - { label: "Abstract", name: "abstract", widget: "text" }
      - { label: "PDF", name: "url_pdf", widget: "string", required: false }
      - { label: "Featured?", name: "featured", widget: "boolean", required: false }
