backend:
  name: github
  repo: DtotheS/hugo-academic-page
  branch: main
  auth_scope: repo
  base_url: https://sianlee.netlify.app
  client_id: Ov23livSWl7NtoOqXJNo  # ← paste your GitHub OAuth App client ID here

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "author"
    label: "Author Profile"
    files:
      - label: "Admin"
        name: "admin"
        file: "content/authors/admin/_index.md"
        fields:
          - { label: "Name", name: "title", widget: "string" }
          - { label: "Role", name: "role", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Organization", name: "organization", widget: "string" }
          - { label: "Bio", name: "bio", widget: "markdown" }
